### ISSUE TITLE
Setup project for running unit tests

### ISSUE THREAD

**Issue by lwjohnst86** [steno-aarhus/seedcase#9]
I'm not familiar with the setup for running unit tests in a non-Python Package setting. @rqding could you set up the files and structure for running automated unit testing for Seedcase?

**Comment by rqding** [comment]
I am a little bit confused about the non-Python setting part. Our current framework mainly uses Django which mainly are Python code, so the unit tests will be running against the Python code mainly.

**Comment by lwjohnst86** [comment]
Yes, I know we are running Python code. The keyword being "Non-Python *Package*". Our project isn't a package, so what's the setup for running unit tests in non-package settings? I know a bit about running tests in package settings, but is it exactly the same in non-package settings?

**Comment by rqding** [comment]
I see your point. So the unit tests for Seedcase would be mostly targeted for Django Code for now, so we would write them in a Python way and probably use the Django test runner tool to run the tests. If in the future we have for example layer of Javascript code, then the unit tests for the Javascript part will use its own test runner to run. If we want to add more control to run the tests, we could write our own script as the configuration/initialization script.
